/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesImport } from './routes/projects/$projectId/environments/$environmentId/features'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesRoute =
  ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesImport.update({
    id: '/projects/$projectId/environments/$environmentId/features',
    path: '/projects/$projectId/environments/$environmentId/features',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/environments/$environmentId/features': {
      id: '/projects/$projectId/environments/$environmentId/features'
      path: '/projects/$projectId/environments/$environmentId/features'
      fullPath: '/projects/$projectId/environments/$environmentId/features'
      preLoaderRoute: typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$projectId/environments/$environmentId/features': typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$projectId/environments/$environmentId/features': typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/projects/$projectId/environments/$environmentId/features': typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/$projectId/environments/$environmentId/features'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/$projectId/environments/$environmentId/features'
  id:
    | '__root__'
    | '/'
    | '/projects/$projectId/environments/$environmentId/features'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesRoute: typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesRoute:
    ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/projects/$projectId/environments/$environmentId/features"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/projects/$projectId/environments/$environmentId/features": {
      "filePath": "projects/$projectId/environments/$environmentId/features.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
