/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesIndexImport } from './routes/projects/$projectId/environments/$environmentId/features/index'
import { Route as ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesFeatureIdImport } from './routes/projects/$projectId/environments/$environmentId/features/$featureId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesIndexRoute =
  ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesIndexImport.update({
    id: '/projects/$projectId/environments/$environmentId/features/',
    path: '/projects/$projectId/environments/$environmentId/features/',
    getParentRoute: () => rootRoute,
  } as any)

const ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesFeatureIdRoute =
  ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesFeatureIdImport.update({
    id: '/projects/$projectId/environments/$environmentId/features/$featureId',
    path: '/projects/$projectId/environments/$environmentId/features/$featureId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/environments/$environmentId/features/$featureId': {
      id: '/projects/$projectId/environments/$environmentId/features/$featureId'
      path: '/projects/$projectId/environments/$environmentId/features/$featureId'
      fullPath: '/projects/$projectId/environments/$environmentId/features/$featureId'
      preLoaderRoute: typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesFeatureIdImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/environments/$environmentId/features/': {
      id: '/projects/$projectId/environments/$environmentId/features/'
      path: '/projects/$projectId/environments/$environmentId/features'
      fullPath: '/projects/$projectId/environments/$environmentId/features'
      preLoaderRoute: typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$projectId/environments/$environmentId/features/$featureId': typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesFeatureIdRoute
  '/projects/$projectId/environments/$environmentId/features': typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$projectId/environments/$environmentId/features/$featureId': typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesFeatureIdRoute
  '/projects/$projectId/environments/$environmentId/features': typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/projects/$projectId/environments/$environmentId/features/$featureId': typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesFeatureIdRoute
  '/projects/$projectId/environments/$environmentId/features/': typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$projectId/environments/$environmentId/features/$featureId'
    | '/projects/$projectId/environments/$environmentId/features'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/$projectId/environments/$environmentId/features/$featureId'
    | '/projects/$projectId/environments/$environmentId/features'
  id:
    | '__root__'
    | '/'
    | '/projects/$projectId/environments/$environmentId/features/$featureId'
    | '/projects/$projectId/environments/$environmentId/features/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesFeatureIdRoute: typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesFeatureIdRoute
  ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesIndexRoute: typeof ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesFeatureIdRoute:
    ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesFeatureIdRoute,
  ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesIndexRoute:
    ProjectsProjectIdEnvironmentsEnvironmentIdFeaturesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/projects/$projectId/environments/$environmentId/features/$featureId",
        "/projects/$projectId/environments/$environmentId/features/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/projects/$projectId/environments/$environmentId/features/$featureId": {
      "filePath": "projects/$projectId/environments/$environmentId/features/$featureId.tsx"
    },
    "/projects/$projectId/environments/$environmentId/features/": {
      "filePath": "projects/$projectId/environments/$environmentId/features/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
